#!/usr/bin/env node
// Generates seeds/02_content.sql from the structured data in seeds/data/*.mjs
// Usage: node seeds/build-seed.mjs
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PARKS } from './data/destinations-parks.mjs';
import { WATER } from './data/destinations-water.mjs';
import { MOUNTAINS } from './data/destinations-mountains.mjs';
import { CULTURE } from './data/destinations-culture.mjs';
import { MORE } from './data/destinations-more.mjs';
import { IMG } from './data/images.mjs';
import { PLACES, ROUTES, FARES } from './data/transport.mjs';
import { GUIDES } from './data/guides.mjs';
import { ITINERARIES } from './data/itineraries.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const REGION = { central: 1, eastern: 2, western: 3, northern: 4 };
const CATEGORY = {
  'national-parks': 1, waterfalls: 2, lakes: 3, mountains: 4, 'cultural-sites': 5, wildlife: 6,
  adventure: 7, islands: 8, cities: 9, historical: 10, forests: 11, birding: 12
};
const FX_UGX_PER_USD = 3750;

const q = (v) => {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
  if (typeof v === 'boolean') return v ? '1' : '0';
  if (Array.isArray(v) || typeof v === 'object') v = JSON.stringify(v);
  return "'" + String(v).replace(/'/g, "''") + "'";
};
const insert = (table, row) =>
  `INSERT INTO ${table} (${Object.keys(row).join(',')}) VALUES (${Object.values(row).map(q).join(',')});`;

const out = [];
out.push('-- AUTO-GENERATED by seeds/build-seed.mjs — do not edit by hand');
out.push('PRAGMA foreign_keys = OFF;');
for (const t of ['destination_guides', 'itinerary_days', 'itineraries', 'travel_guides', 'accommodations',
  'transport_fares', 'transport_routes', 'places', 'gallery_images', 'activities', 'destination_categories', 'destinations'])
  out.push(`DELETE FROM ${t};`);

// ---------- Destinations ----------
const ALL = [...PARKS, ...WATER, ...MOUNTAINS, ...CULTURE, ...MORE];
const destId = {};
ALL.forEach((d, i) => {
  const id = i + 1;
  destId[d.slug] = id;
  const img = IMG[d.slug] || {};
  out.push(insert('destinations', {
    id, slug: d.slug, name: d.name, short_name: d.short_name, tagline: d.tagline,
    region_id: REGION[d.region], district: d.district, location_label: d.location_label,
    latitude: d.lat, longitude: d.lng, hero_image: img.hero, card_image: img.card || img.hero,
    intro: d.intro, overview: d.overview, why_visit: d.why_visit, getting_there: d.getting_there,
    travel_advice: d.travel_advice, highlights: d.highlights, wildlife: d.wildlife,
    what_to_pack: d.what_to_pack, nearby: d.nearby, best_time: d.best_time,
    best_time_detail: d.best_time_detail, climate_note: d.climate_note,
    distance_from_kampala_km: d.km_from_kampala, drive_hours_min: d.drive_min, drive_hours_max: d.drive_max,
    cost_from_ugx: d.cost_from_ugx, entry_fee_foreign_usd: d.fee_usd, entry_fee_eastafrican_ugx: d.fee_ugx,
    entry_fee_note: d.fee_note, experience_tags: d.experience, budget_level: d.budget_level,
    budget_levels: d.budget_levels, recommended_days: d.recommended_days, duration_band: d.duration_band,
    difficulty: d.difficulty, popularity: d.popularity ?? 50, featured: d.featured ? 1 : 0,
    seo_title: `${d.name} — Travel Guide, Costs & How to Get There | Discover Uganda`,
    seo_description: (d.intro || '').slice(0, 155), og_image: img.card || img.hero
  }));
  for (const c of d.categories || []) {
    if (CATEGORY[c]) out.push(insert('destination_categories', { destination_id: id, category_id: CATEGORY[c] }));
  }
  (d.activities || []).forEach((a, j) => {
    out.push(insert('activities', {
      destination_id: id, slug: a.slug, name: a.name, icon: a.icon, description: a.description,
      duration: a.duration, difficulty: a.difficulty, cost_usd_min: a.usd_min, cost_usd_max: a.usd_max,
      cost_ugx_min: a.usd_min != null ? Math.round(a.usd_min * FX_UGX_PER_USD) : null,
      cost_ugx_max: a.usd_max != null ? Math.round(a.usd_max * FX_UGX_PER_USD) : null,
      cost_note: a.cost_note, recommended_age: a.age, what_to_bring: a.bring || [],
      best_season: a.season, experience_tag: a.tag, sort: j
    }));
  });
  (img.gallery || []).forEach(([url, caption, category], j) => {
    out.push(insert('gallery_images', {
      destination_id: id, url, caption, category, credit: 'Licensed imagery', featured: j === 0 ? 1 : 0, sort: j
    }));
  });
});

// ---------- Demo accommodation (clearly flagged) ----------
const ACC_TIERS = [
  ['budget', 'Campsite & Bandas', 'banda', 25, 60, 'per person', ['Shared bathrooms', 'Camping pitches', 'Restaurant']],
  ['midrange', 'Safari Lodge', 'lodge', 150, 280, 'per person sharing, full board', ['En-suite rooms', 'Restaurant & bar', 'Wi-Fi in lounge', 'Guided walks']],
  ['luxury', 'Luxury Tented Camp', 'lodge', 450, 1100, 'per person sharing, all-inclusive', ['Private deck', 'Spa', 'Infinity pool', 'Private guide', 'All meals & drinks']]
];
for (const d of ALL) {
  for (const [cat, suffix, type, min, max, basis, amen] of ACC_TIERS) {
    if (!(d.budget_levels || []).includes(cat)) continue;
    const img = IMG[d.slug] || {};
    out.push(insert('accommodations', {
      destination_id: destId[d.slug], name: `${d.short_name || d.name} ${suffix}`,
      slug: `${d.slug}-${cat}`, category: cat, property_type: type,
      image: (img.gallery && img.gallery[cat === 'budget' ? 1 : cat === 'midrange' ? 2 : 3]?.[0]) || img.card,
      location_label: d.location_label, distance_from_attraction: cat === 'luxury' ? '5–15 min drive' : 'Within 30 min',
      price_usd_min: min, price_usd_max: max, price_basis: basis, amenities: amen,
      data_source: 'demo', is_demo: 1,
      notes: 'Illustrative listing showing typical price bands for this tier. Not a real property — confirm options with a licensed operator.'
    }));
  }
}

// ---------- Places ----------
const placeId = {};
PLACES.forEach(([slug, name, kind, region, lat, lng, hub, strip], i) => {
  placeId[slug] = i + 1;
  const destMatch = ALL.find((d) => d.slug === slug);
  out.push(insert('places', {
    id: i + 1, slug, name, kind, region_id: REGION[region], latitude: lat, longitude: lng,
    is_hub: hub, has_airstrip: strip, destination_id: destMatch ? destId[slug] : null
  }));
});
// Map endpoint places to their destinations for "how to get there"
const PLACE_TO_DEST = {
  paraa: 'murchison-falls-national-park', apoka: 'kidepo-valley-national-park', buhoma: 'bwindi-impenetrable-national-park',
  katunguru: 'queen-elizabeth-national-park', kanyanchu: 'kibale-national-park', nshara: 'lake-mburo-national-park',
  rutinda: 'lake-bunyonyi', ziwa: 'ziwa-rhino-sanctuary', mabamba: 'mabamba-swamp', najjembe: 'mabira-forest',
  bujagali: 'bujagali', ntebeko: 'mgahinga-gorilla-national-park', nyakalengija: 'rwenzori-mountains-national-park',
  budadiri: 'mount-elgon-national-park', sempaya: 'semuliki-national-park', sipi: 'sipi-falls', bugala: 'ssese-islands',
  jinja: 'jinja', kampala: 'kampala', entebbe: 'entebbe', 'fort-portal': 'fort-portal', moroto: 'pian-upe-wildlife-reserve'
};
for (const [p, d] of Object.entries(PLACE_TO_DEST))
  if (placeId[p] && destId[d]) out.push(`UPDATE places SET destination_id=${destId[d]} WHERE id=${placeId[p]};`);

// ---------- Routes & fares ----------
const routeId = {};
ROUTES.forEach(([from, to, km, hmin, hmax, road, wp, transfers, notes, alt], i) => {
  const slug = `${from}-to-${to}`;
  routeId[slug] = i + 1;
  out.push(insert('transport_routes', {
    id: i + 1, from_place_id: placeId[from], to_place_id: placeId[to], slug, distance_km: km,
    duration_hours_min: hmin, duration_hours_max: hmax, road_quality: road, route_description: notes,
    waypoints: wp, alt_waypoints: alt ? alt.wp : null, alt_distance_km: alt ? alt.km : null,
    alt_note: alt ? alt.note : null, transfers, notes, data_confidence: 'curated'
  }));
});
for (const [slug, mode, min, max, hmin, hmax, notes] of FARES) {
  out.push(insert('transport_fares', {
    route_id: routeId[slug], mode, fare_min_ugx: min, fare_max_ugx: max,
    duration_hours_min: hmin, duration_hours_max: hmax,
    per_person: ['private_car', 'tourist_van', 'special_hire'].includes(mode) ? 0 : 1, notes
  }));
}

// ---------- Guides ----------
const heroFor = (slug) => (IMG[slug] && (IMG[slug].hero || IMG[slug].card)) || null;
GUIDES.forEach((g, i) => {
  out.push(insert('travel_guides', {
    id: i + 1, slug: g.slug, title: g.title, category: g.category, subcategory: g.subcategory,
    excerpt: g.excerpt, body: g.body, hero_image: heroFor(g.destinations?.[0]), icon: g.icon,
    read_minutes: g.read_minutes, tags: g.tags, featured: g.featured, sort: i,
    seo_title: `${g.title} | Discover Uganda`, seo_description: g.excerpt
  }));
  for (const d of g.destinations || [])
    if (destId[d]) out.push(insert('destination_guides', { destination_id: destId[d], guide_id: i + 1 }));
});

// ---------- Itineraries ----------
ITINERARIES.forEach((it, i) => {
  const id = i + 1;
  const total = it.schedule.reduce((s, d) => s + (d[6] || 0), 0);
  out.push(insert('itineraries', {
    id, slug: it.slug, title: it.title, subtitle: it.subtitle, days: it.days, theme: it.theme,
    region_focus: it.region_focus, summary: it.summary, hero_image: heroFor(it.hero),
    total_distance_km: total, cost_ugx_min: it.cost_ugx_min, cost_ugx_max: it.cost_ugx_max,
    best_for: it.best_for, tips: it.tips, featured: it.featured
  }));
  it.schedule.forEach(([title, dslug, label, desc, acts, transport, km, acc, tip], j) => {
    out.push(insert('itinerary_days', {
      itinerary_id: id, day_number: j + 1, title, destination_id: dslug ? destId[dslug] ?? null : null,
      destination_label: label, description: desc, schedule: [], activities: acts, transport,
      distance_km: km, accommodation: acc, tip: tip || null
    }));
  });
});

out.push('PRAGMA foreign_keys = ON;');
const file = join(here, '02_content.sql');
writeFileSync(file, out.join('\n') + '\n');
console.log(`Wrote ${file}: ${ALL.length} destinations, ${ROUTES.length} routes, ${GUIDES.length} guides, ${ITINERARIES.length} itineraries`);
